### ISSUE TITLE
Color theme is not working correctly with telescope before opening a file

### ISSUE THREAD

**Issue by homerosbart2** [siduck76/NvChad#2115]
**Describe the bug**
First, I don't know if this is related to NvChad configuration or Telescope. When I open `nvim` and press `<leader> + ff` it opens telescope, but it is not using my theme in the "File Preview" section. After opening a file it works.

**To Reproduce**
1. Open nvim
2. Press `<leader> + ff`

**Expected behavior**
To use palenight theme correctly everywhere.

**Screenshots**
**Before opening a file**|**After opening a file**
---|---
![image](https://github.com/NvChad/NvChad/assets/25249581/6f72ad93-8199-4cb9-bde7-fd6e795b6a79)|![image](https://github.com/NvChad/NvChad/assets/25249581/ed6c45ee-3c43-4c84-ae60-143ea992fcef)

**Desktop (please complete the following information):**
- Operating System: macOS 13.1 Beta
- Terminal: iTerm2
- Version of Neovim: v0.9.1

**Comment by siduck** [comment]
update nvchad, this issue was fixed already https://github.com/NvChad/NvChad/issues/2084

**Comment by homerosbart2** [comment]
I did before creating the issue, but this is still happening to me 🤔 

![image](https://github.com/NvChad/NvChad/assets/25249581/f843dd33-beb0-4649-b009-7d297cf091d1)

**Comment by siduck** [comment]
> I did before creating the issue, but this is still happening to me thinking
> 
> ![image](https://user-images.githubusercontent.com/25249581/245700076-f843dd33-beb0-4649-b009-7d297cf091d1.png)

reopen neovim

**Comment by homerosbart2** [comment]
👀 I'm reopening after updating.

https://github.com/NvChad/NvChad/assets/25249581/65b4e972-b0c0-49c1-aa07-1ac77fe43625

**Comment by siduck** [comment]
weird, can you try just vanillla nvchad and check? delete .local/share/nvim before

**Comment by homerosbart2** [comment]
![image](https://github.com/NvChad/NvChad/assets/25249581/7b595305-2853-4bf7-989d-c93db8bad784)

It works with vanilla nvchad 🤔 probably it is because of my `chadrc.lua`?

![image](https://github.com/NvChad/NvChad/assets/25249581/b89d25dc-aebc-448d-b378-8028cf5fcc7b)

**Comment by siduck** [comment]
@homerosbart2  yes most probably! just check your custom plugins file or else, comment sections in chadrc one by one.

**Comment by homerosbart2** [comment]
I couldn't find the problem 👀 but after reinstalling and setting up everything again I noticed that after running `:NvChadUpdate` now it says `Already updated!`, that never happened when I was trying to solve this (I did run the command many times). So probably I changed something outside `custom` directory by mistake 🤦🏼‍♂️ and it was not updating successfully.
