### ISSUE TITLE
'fzf' extension doesn't exist or isn't installed

### ISSUE THREAD

**Issue by AhsanSarwar45** [siduck76/NvChad#2571]
**Describe the bug**
Starting telescope throws this error
![image](https://github.com/NvChad/NvChad/assets/41967492/6794bc7f-10cb-4459-aef3-4d09245feb46)

`make` and `gcc` are installed and in the path:
![image](https://github.com/NvChad/NvChad/assets/41967492/b6e46d60-5f28-48a2-ac98-e5296da40785)

**To Reproduce**
1. Fresh Install NvChad
2. Open nvim
3. Press `<leader>ff`
4. Error shows up

**Expected behavior**
No error should show

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Terminal: Windows Terminal
 - Version of Neovim: 0.9.4

**Additional context**
Tried building fzf-native myself using and the cmake and the error still shows up.
`cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`
```pwsh

    Directory: C:\Users\ahsan\AppData\Local\nvim-data\lazy\telescope-fzf-native.nvim\build

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           23-Dec-23  8:10 AM                CMakeFiles
-a---           23-Dec-23  8:10 AM           3859 cmake_install.cmake
-a---           23-Dec-23  8:10 AM          13970 CMakeCache.txt
-a---           23-Dec-23  8:10 AM              0 install_manifest.txt
-a---           23-Dec-23  8:10 AM          11884 libfzf.dll.a
-a---           23-Dec-23  8:10 AM          34268 libfzf.so
-a---           23-Dec-23  8:10 AM           7360 Makefile
```
Tried running `gcc -O3 -Wall -Werror -fpic -shared src/fzf.c -o build/libfzf.dll` after that, and nvim crashes when using telescope.

**Comment by siduck** [comment]
not a nvchad issue then :/ 

@kayuxx ig its time to remove this plugin, 90% of issues we get regarding this are from windows users

**Comment by siduck** [comment]
does the thing compile tho?

**Comment by AlexanderHott** [comment]
found this is an issue in the lunar vim repo https://github.com/LunarVim/LunarVim/issues/1804#issuecomment-1742557504

`cd ~/.local/share/nvim/lazy/telescope-fzf-native.nvim && make && cd -`

and it worked for me

**Comment by kayuxx** [comment]
@siduck i see that most issues on that topic even though, it improve performance removing it is not a good idea

**Comment by kayuxx** [comment]
@AhsanSarwar45 did u have `make` and `gcc` installed in your system before NvChad install?, if not this probably cause to fail the compiling.
and for the fix run this command `cd ~/.local/share/nvim/lazy/telescope-fzf-native.nvim && make && cd -`
this should work for you

**Comment by siduck** [comment]
> @siduck i see that most issues on that topic even though, it improve performance removing it is not a good idea

yes users can add it in custom plugins. and its not good to manually CD and fix it imo.

**Comment by larsx2** [comment]
I just updated NvChad and got another variant of the error of this Issue. This is from a fresh install and didn't see it before I updated the code.

![image](https://github.com/NvChad/NvChad/assets/451243/5e9b10d0-ce4d-4b94-b442-514129b36f77)

**Comment by siduck** [comment]
@larsx2 can you make a video of clean nvchad installation ( delete all old dirs ) and show here

**Comment by karimkhaleel** [comment]
@larsx2 I had the same error show up after this update. I reinstalled (removed old directories as well) and it still showed up.

Fixed it by adding this to custom plugins:
`  {
    "nvim-telescope/telescope-fzf-native.nvim",
    build = "cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build",
  }
`

Just make sure you have cmake installed. I didn't have it installed the first time I added this line to my config and it failed to build it and then didn't want to rebuild it until I ran `:Lazy build telescope-fzf-native.nvim`.

Seems to be working fine now.

**Comment by siduck** [comment]
ok properly removed now

**Comment by rendivs925** [comment]
> @AhsanSarwar45 did u have `make` and `gcc` installed in your system before NvChad install?, if not this probably cause to fail the compiling. and for the fix run this command `cd ~/.local/share/nvim/lazy/telescope-fzf-native.nvim && make && cd -` this should work for you

it works !!!!!!!!!!!!
